file = open("files/3_0_file_read_R_mode.txt", "r")
print("Reading Data of First Line Data\n")
print(file.readline())
print(file.readline())
print(file.readline())
print(file.readline())
file.close()
